### PR TITLE
scikit-image handout

### PR DESCRIPTION
**Pull request by JDWarner**
First public draft of the `scikit-image` handout. Comments welcome. This is loosely based on the `Tufte-LaTeX/tufte-latex` handout theme, but I've customized it heavily. The idea was to have a professionally created, two-sided, single page document available to hand out to tutorial attendees or from an open source table.

This is a fully reproducible document. `cd` into `skimage-media/handout` and run `make`, which
- Cleans the directory of any temporary files
- Generates and saves figures with individual Python scripts
- Runs the necessary LaTeX routines to build the document
  - pdflatex
  - bibtex
  - pythontex
  - pdflatex
  - pdflatex (just to be sure)
- Clips the final, wasted page which contains only a redundant bibliography

I have used only the minimal necessary media files to keep the repo size down, so no example version of the handout PDF is included. However, at time of submission it should look like this: [handout.pdf](https://github.com/scikit-image/skimage-media/files/246/handout.pdf) **(new link lower, scroll down)**

### CODE REVIEW

**Comment by JDWarner** [comment]
Ping @stefanv, @blink1073 - How does this look to you? I wrestled with LaTeX for a while trying to get a symmetric two-column layout going, Stefan, and it wasn't working well. So I opted to fall back on the style of Edward Tufte.

This won't fold in half, but I actually think it works better.

**Comment by vighneshbirodkar** [comment]
References are missing.

**Comment by JDWarner** [comment]
There is very limited space. The only actual reference is to the scikit-image paper, and the citation for this style is inline (in the sidebar, to the right). The bibliography is redundant with that citation, so it's pushed onto a third page and clipped. Superscripts use the `\footnote` command, which in this style prints to the right column, for figure captions to save room.

**Comment by blink1073** [comment]
This looks great @JDWarner, thank you!  It would be nice to have a link to the PDF in the intro notebook, in case folks want a soft copy.  By the way, what was the mechanism for uploading that file?

**Comment by JDWarner** [comment]
Drag and drop! GitHub magic. Works just like an image in the post, except no preview.

Tried it on a whim... I didn't expect it to work, to be honest ;)

**Comment by blink1073** [comment]
Excellent, free perma-link.

**Comment by JDWarner** [comment]
[Updated handout PDF](https://github.com/scikit-image/skimage-media/files/505/handout.pdf)
 including the latest three commits. All live functions on reverse side now properly colored DarkBlue.

**Comment by blink1073** [comment]
Works for me, merging.  Thanks @JDWarner!

**Pull request merged**
